### PR TITLE
Update custom types

### PR DESCRIPTION
**Pull request by swflint**
This is a start to improve my issue in #73 and should help move towards #74 as well.

### CODE REVIEW

**Comment by swflint** [comment]
Please hold off on merging this, I just realized you have this as copyright the FSF.  I'm currently waiting for my employer to finally sign a disclaimer so that I can contribute to emacs-related projects.

**Comment by armindarvish** [comment]
@swflint Alright, let me know when your employer gives you the OK.

**Comment by swflint** [comment]
I'm going to close this, I have no clue when that's going to happen.  However, I'm going to make some bug reports for some broken customization types.

**Comment by armindarvish** [comment]
@swflint, Ok, I appreciate the suggestions and if I find time, I can still try to implement some of those suggestions if you don't mind (without directly merging your commits, so your employer won't have to worry about it!)

On the topic of submitting this to MELPA, that would be great. I just have not gone through that process before and have been busy with some other projects/packages, therefore I did not get around working on that. If you know the process and can give me some hints, I'd really appreciate it. I will likely have some more time at the end of the year and can work on that.

**Comment by swflint** [comment]
I'd love to help.  I've successfully submitted a few packages.  Realistically, there are ~3 things you'll need to do.

 - Run `M-x checkdoc` on all the elisp files
 - Run `M-x byte-compile-file` on all of the elisp files.
 - Install [`package-lint`](https://github.com/purcell/package-lint) and run `package-lint-buffer` on all of the elisp files.

If you can get it to a point where it won't complain (too much), getting the package into MELPA should be pretty easy.

**Pull request closed without merging**
